-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "buyingPrice" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "totalBuyingPrice" SET DATA TYPE DECIMAL(18,4);
