/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScreenerRouteImport } from './routes/_app.screener'
import { Route as AppRetirementRouteImport } from './routes/_app.retirement'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppHoldingsRouteImport } from './routes/_app.holdings'
import { Route as AppGoalsRouteImport } from './routes/_app.goals'
import { Route as AppDividendsRouteImport } from './routes/_app.dividends'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppPortfolioIndexRouteImport } from './routes/_app.portfolio.index'
import { Route as AppStockSymbolRouteImport } from './routes/_app.stock.$symbol'
import { Route as AppPortfolioIdRouteImport } from './routes/_app.portfolio.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenerRoute = AppScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppRetirementRoute = AppRetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsRoute = AppHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDividendsRoute = AppDividendsRouteImport.update({
  id: '/dividends',
  path: '/dividends',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioIndexRoute = AppPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AppRoute,
} as any)
const AppStockSymbolRoute = AppStockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioIdRoute = AppPortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/dividends': typeof AppDividendsRoute
  '/goals': typeof AppGoalsRoute
  '/holdings': typeof AppHoldingsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/retirement': typeof AppRetirementRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/portfolio/$id': typeof AppPortfolioIdRoute
  '/stock/$symbol': typeof AppStockSymbolRoute
  '/portfolio/': typeof AppPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/dividends': typeof AppDividendsRoute
  '/goals': typeof AppGoalsRoute
  '/holdings': typeof AppHoldingsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/retirement': typeof AppRetirementRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/': typeof AppIndexRoute
  '/portfolio/$id': typeof AppPortfolioIdRoute
  '/stock/$symbol': typeof AppStockSymbolRoute
  '/portfolio': typeof AppPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dividends': typeof AppDividendsRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/holdings': typeof AppHoldingsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/retirement': typeof AppRetirementRoute
  '/_app/screener': typeof AppScreenerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/_app/': typeof AppIndexRoute
  '/_app/portfolio/$id': typeof AppPortfolioIdRoute
  '/_app/stock/$symbol': typeof AppStockSymbolRoute
  '/_app/portfolio/': typeof AppPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/dividends'
    | '/goals'
    | '/holdings'
    | '/notifications'
    | '/reports'
    | '/retirement'
    | '/screener'
    | '/settings'
    | '/transactions'
    | '/watchlist'
    | '/portfolio/$id'
    | '/stock/$symbol'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/calendar'
    | '/dividends'
    | '/goals'
    | '/holdings'
    | '/notifications'
    | '/reports'
    | '/retirement'
    | '/screener'
    | '/settings'
    | '/transactions'
    | '/watchlist'
    | '/'
    | '/portfolio/$id'
    | '/stock/$symbol'
    | '/portfolio'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/calendar'
    | '/_app/dividends'
    | '/_app/goals'
    | '/_app/holdings'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/retirement'
    | '/_app/screener'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/watchlist'
    | '/_app/'
    | '/_app/portfolio/$id'
    | '/_app/stock/$symbol'
    | '/_app/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screener': {
      id: '/_app/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof AppScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retirement': {
      id: '/_app/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof AppRetirementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holdings': {
      id: '/_app/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof AppHoldingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dividends': {
      id: '/_app/dividends'
      path: '/dividends'
      fullPath: '/dividends'
      preLoaderRoute: typeof AppDividendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio/': {
      id: '/_app/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AppPortfolioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/$symbol': {
      id: '/_app/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof AppStockSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio/$id': {
      id: '/_app/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof AppPortfolioIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDividendsRoute: typeof AppDividendsRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppHoldingsRoute: typeof AppHoldingsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRetirementRoute: typeof AppRetirementRoute
  AppScreenerRoute: typeof AppScreenerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPortfolioIdRoute: typeof AppPortfolioIdRoute
  AppStockSymbolRoute: typeof AppStockSymbolRoute
  AppPortfolioIndexRoute: typeof AppPortfolioIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDividendsRoute: AppDividendsRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppHoldingsRoute: AppHoldingsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRetirementRoute: AppRetirementRoute,
  AppScreenerRoute: AppScreenerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppPortfolioIdRoute: AppPortfolioIdRoute,
  AppStockSymbolRoute: AppStockSymbolRoute,
  AppPortfolioIndexRoute: AppPortfolioIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
